### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'max_acc_corresponding_metrics'

### ISSUE THREAD

**Issue by bryanzhang1024** [Marigoldwu/A-Unified-Framework-for-Deep-Attribute-Graph-Clustering#2]
Error message:
Traceback (most recent call last):
  File "main.py", line 53, in <module>
    result = train(args, data, logger)
  File "/home/ubuntu/project/graph-clustering/A-Unified-Framework/model/SDCN/train.py", line 78, in train
    result = Result(embedding=embedding, max_acc_corresponding_metrics=max_acc_corresponding_metrics)
TypeError: __init__() got an unexpected keyword argument 'max_acc_corresponding_metrics'

Solution:
in /utils/result.py
change `acc_max_corresponding_metrics` to `max_acc_corresponding_metrics`

**Comment by Marigoldwu** [comment]
Thanks for pointing out the problem! We also found the problem several days ago, but due to our negligence, we forgot to upload the changed code. We have fixed this problem. Thanks again!
