### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by Ljwccc** [Marigoldwu/A-Unified-Framework-for-Deep-Attribute-Graph-Clustering#4]
感谢作者这么优异的工作，想请教下作者现在用AE来做深度聚类的模型，有base结构是GraphSAGE来做的吗

**Comment by Marigoldwu** [comment]
感谢您对本工作的认可！在我看来，GraphSAGE是GCN在大规模图上的升级版，因此使用GCN（GAE）的模型几乎都可以将其中的GNN替换为GraphSAGE，想了解更多使用图做聚类的方法可参考这个仓库（ https://github.com/yueliu1999/Awesome-Deep-Graph-Clustering ），如有理解不对的地方，欢迎批评指正！
