### ISSUE TITLE
无法复现AGCN的性能

### ISSUE THREAD

**Issue by zr-swu** [Marigoldwu/A-Unified-Framework-for-Deep-Attribute-Graph-Clustering#5]
你好，感谢你这么优异的工作，想请教下为什么通过此框架中复现的AGCN获得的性能不如原作者提供的模型（低3%-4%）。

**Comment by Marigoldwu** [comment]
@zr-swu 您好，感谢对本工作的关注！AGCN源代码中没有使用随机数种子，可尝试将main.py中设置随机数种子的代码注释掉，然后重新进行预训练，由于源代码也未提供预训练代码，所以复现还是困难的。可多次尝试预训练，并通过聚类来检测预训练的效果，选择较好的预训练参数。另外，我注意到AGCN中的对称归一化是非对称归一化D^-1A，可尝试加上-SF指令看看效果， 还有在model.py中GCN，源代码中使用的LeakyReLU激活，所以也需要加上激活类型，这个地方是我疏忽了。最后，不必追求完全复现论文中的结果，只要我们自己提出的方法可以复现就行了，对于别人的代码和论文，理解idea即可。如果本工作对您有帮助，给个star鼓励一下！

**Comment by Marigoldwu** [comment]
> 你好，感谢你这么优异的工作，想请教下为什么通过此框架中复现的AGCN获得的性能不如原作者提供的模型（低3%-4%）。

我又试了下，实际上对称归一化效果更好，对于ACM来说如果预训练能到0.85左右的话，最终结果会在0.90左右，所以可以多尝试一下。或者你直接用原文提供的代码进行尝试。

**Comment by zr-swu** [comment]
感谢你宝贵的建议，我发现预训练的性能确实很影响模型的最终性能。我想复现论文的性能是因为我刚入门该领域  想在现有研究基础上做改进。
